### ISSUE TITLE
Listing by shift is creating too much noise in the list

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#107]
I know it's sample data, but for me to get to the middle of may, where I might have some time to volunteer, I will have to push - view more - 30 or so times.

one solution could be to go by day, then have a hidden element that shows when the event is tapped which will be a list of shifts that will lead to the shift detail page

another would be to have an event page instead of a shift page. This is the solution I have always preferred and I'm curious to hear the feedback now that the list actually exists now.

**Comment by klappradla** [comment]
Useful feedback, I totally get your point.

I'm not sure though if I got your first approach right. So you mean: display the event / day and then on click expand it to also view its shifts? Sounds promising I'd say.

For approach nr. 2: a list of events, then an event page listing all shifts and a **`help`** button for each shift? I would not know from scratch how to place these elements on the event page yet though.

**Comment by markusrubey** [comment]
I agree, definitely a pain point currently, but for version one I would say it's okay. One could improve it as @klappradla mentioned by collapsing all events inside the list and expand it on selection.

**Comment by klappradla** [comment]
So [here](https://github.com/where2help/where2help/tree/108)'s the current state of trying out an events- instead of shifts-list.
What's currently a bit inconsistent: the event show view listing all shifts also displays past and full ones. But there's now a (then to be private) instance method in place on the event model to scope its shifts accordingly: [`available_shifts`](https://github.com/where2help/where2help/blob/108/app/models/event.rb#L52)

Adopting the specs to it is still kind of a pain... 🙈

**Comment by klappradla** [comment]
So, the event-orientated UI-approach is on master + on staging + on fsw app. Views are not super accurate, yet, but I'll address this in separate issues then.

@pferdefleisch take a look at it - if it fits what you though could be an improvement, we could close this one.

**Comment by markusrubey** [comment]
So @pferdefleisch how are you going to implement it on iOS?

The current implementation on Android is the one you saw in the demo video. But I would much rather prefer having shifts somehow on the detail screen of an event like @klappradla 's current "event-orientated UI-approach".

**Comment by markusrubey** [comment]
Followup: Could we agree on one solution across platforms?

**Event Screen:**
I would leave it as is currently on staging. Not sure about the volunteer counter though. Maybe remove the counter from the list and only show it on detail for each shift.

**Schedule Screen:**
I would suggest to have it like on Android currently (see attachment) 
![device-2016-05-14-125901](https://cloud.githubusercontent.com/assets/2398384/15268045/be51d5fe-19d3-11e6-9086-4a3b32893a26.png)

**Comment by klappradla** [comment]
Yes, I’d be fine with this solution (actually like it a lot). It’s a bit more css work to implement, but far from magic.
+1 on using this layout

**Comment by markusrubey** [comment]
Regarding the counter, maybe we should drop the whole idea of it? On the event screen at least there is point in it. On the Schedule and Event Detail screen maybe, but I don't see a clear use case for the user anyways.

**Comment by markusrubey** [comment]
Okay, having the list without shifts on Events and the list with shifts on Schedule feels confusing. Because on one you launch into an Detail Screen with all available shifts and on the other you launch into a single shift(?). I think it's better to have the list inside Schedule the same as the list in Events and only show the shifts the user signed up to when launching into the Details screen fro Schedule. Or maybe even keep the Detail screens the same? Would result in much less work and is more user friendly in my eyes. 

(@pferdefleisch, again, what are your thoughts on this regarding iOS?)

**Comment by klappradla** [comment]
Good point!
The schedule currently lists shifts, not events. So it would be kind of weird to link to events from it *(I should probably update the respective issue on this)*.

**Lists**
Regarding the differences between **Events** and **Schedule**: I don't see the necessity to have the lists look the same, as they do actually display different things. The **Schedule** is currently kind of *broken*, since we moved to the Event-list on **Events** and while that changed some partials that were also used for the schedule.
We need to fix this and use separate partials again *(I will for now just assign the respective issue to me)* and then later take care of that.

**Counter**
I think it makes sense in several places, as it gives a nice additional info for the user and maybe even raises the importance of certain items. For the **Schedule** it doesn't and I would remove it there.
For the **Event** list, it makes sense, as it also tells the user in which events she already opted in for a shift (badge has different color then).
For the list of shifts in the event's detail screen, it also makes sense I'd say, as it shows the user how big the shifts are and what she can expect there. It makes a difference if you work with 50 other or 5 other people, so I guess its a usable piece of information here.

**Comment by markusrubey** [comment]
**Schedule**
Could you elaborate on how you intend the Schedule to be? If you stick to listing shifts, as a user, I would miss the title of the event. Following up on that: If you are signed up for more than one shift of an event you would clutter the list with the same title over and over again - just for another time slot. 

Unclear to me is also what the detail screen of an shift from the Schedule list should be in this case. An Event detail screen with just one time slot? The advantage of linking to the same Event Detail Page as from Events is that the user could opt into more time slots or switch to a later time slot right from his Schedule.

**Counter**
I agree, could be a valuable motivation factor for some. So on Event items we show a sum of what's needed in all related shifts, and on Event Detail we show it per shift. 👍

**Comment by klappradla** [comment]
Yes, been thinking about this too. I see two reasonable approaches:

1. **The Schedule lists Evens (same as the Event list)**  
  From there on, clicking on an event would lead to an event detail view including **all** shifts (not just upcoming ones), telling the user on first glance which shifts she opted in and when she has to be where.
2. **The Schedule lists shifts**  
  The schedule lists shifts, each items containing date, time and event-title. Clicking on a shift will lead to a shift detail view *(looking like our old shift detail view, now event detail view)* providing all additional information about the event and the possibility to opt out of this one shift.

I personally favor approach nr. 2.
It can possibly lead to the same event title showing up multiple times, that's right. But I don't see this as a problem, as it a) is unlikely to happen too frequently in real world use and b) still gives a better overview on someones actual "Schedule" as in "when do I have to be where".

**Comment by klappradla** [comment]
I quickly implemented approach nr. 2 *(will be on staging in a few seconds + I'll repopoulate the db there)*. Would be nice, if you could take a quick look @markusrubey if the schedule now makes more sense.

This is what it does:
- it lists shifts
- clicking on a shift leads to a shift detail view

The shift detail view is basically the same as the event's detail view, but scoped down to just one single shift, regarding time-information and button-interaction.

**Comment by markusrubey** [comment]
Cool, I thought about it and it kinda makes sense. Cause if you attend a shift of an event between two shifts of another event you would need the title again, otherwise you couldn't list shifts like an agenda. There is always room for improvement but I think it's fine for now.
