### ISSUE TITLE
Separate or combine web/api controllers?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#142]
I am currently getting an overview of the code base and noticed that there are different controllers for the [web app](https://github.com/where2help/where2help/blob/master/app/controllers/shifts_controller.rb) and the [mobile API](https://github.com/where2help/where2help/blob/master/app/controllers/api/v1/shifts_controller.rb) (e.g. `/shifts/<id>/opt_in` and `/api/v1/shifts/<id>/opt_in`). Since the business logic is quite similar (from what I have seen so far), I was wondering what other reasons may be involved in the decision to keep them separated. Would it be possible to combine them into one controller and use `respond_to do |format|` blocks to decide whether to return HTML or JSON? Would it be a good idea?

* Duplicate business logic vs. DRY
* HTML vs JSON
* Versioned API vs. Unversioned API
* Cookie Authentication vs. Token Authentication
* CSRF Protection vs. No CSRF Protection
* ...?

**Comment by haslinger** [comment]
As I did most of the api, here are my 2cents: 
You actually gave some of my reasons yourself. My arguments are:
- As you said. they are quite similar, but not always the same. 
- In this situation I prefer separation of concerns of DRYness.
- Files stay smaller
- In coding sessions, it is easier not to interfere with each other. 
- An API should be versioned. (I was planning ahead to use even different API's for the Android and the IOS apps, which turned out not to be necessary)
- As you wrote, authentication and CSRF are different.
- It worked out well in the first iteration (we are now on the second one).
- There was an issue with Android sending wrong response headers (which caused the app to respond with HTML instead of JSON). This way we can assume and override wrong response headers in the routes file.

The big change from the first iteration was the decision not to use devise-token-auth and jsonapi-ressources any more which were a pain to configure and tweak in comparison to writing the stuff myself.

**Comment by klappradla** [comment]
Yes, I also think one core reason was the difference regarding authentication. Don't really know if there's a huge benefit in trying to dry these things up though. Do you think thinks would be better to maintain @groe ?

**Comment by groe** [comment]
Thanks a lot for the explanations!

I think if the business logic would basically be the same (and there were no plans that they would divert in the future), having a single place would be preferable. Authentication and CSRF handling both can be taken care of in `before_action`s and JSON/HTML handling should only be a few lines of code if the business logic is the same.

But that's not the case here apparently. The logic is slightly different and could divert even more in the future. Also, @haslinger's arguments on coding sessions being easier and API versioning totally make sense.

I have had a similar situation in another project where merging the business logics was preferable, so I thought I'd bring it up for discussion here as well. But I'm convinced, no reason to change the current structure :) Thanks again!
