### ISSUE TITLE
Use letter_opener for email testing?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#149]
I have found [letter_opener](https://github.com/ryanb/letter_opener) very useful in development environments to see sent emails in the browser, especially when they are HTML formatted. It's basically a drop-in solution.

Would it be helpful for where2help as well? How do you test emails so far?

**Comment by klappradla** [comment]
We had the `letter_opener` gem for sending email in development in the first iteration of this app (Rails 4 app). From what I remember, the reason why I dropped it was, that it tends to get annoying once you start sending a lot of automated email in the background - it just opens tabs over and over 🙈 

For now, I just view things in the terminal (I can also click links there).

If you really want to *test* HTML emails and how the look like, are rendered, etc., utilizing `ActionMailer::Preview` might be an even better approach, because you spare clicking around and creating the necessary *"scenario"* around sending these mails by hand.

Dropping in something like this will allow you to just point your browser to `/rails/mailers` to view HTML rendered email:
````ruby
# spec/mailers/preview/user_mailer_preview.rb

class UserMailerPreview < ActionMailer::Preview
  def welcome
    UserMailer.welcome(User.last)
  end
end
```

Anyways, if `letter_opener` suits your workflow, feel free to set it up for development. Same for `ActionMailer::Preview` specs: feel free to add them if this helps you.

**Comment by groe** [comment]
@klappradla Woah, `ActionMailer::Preview` looks great, thanks for the hint!

If `letter_opener` got more of an annoyance, let's waive it. The AM::Previews enable mail previews anyway (even better).
