### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by groe** [where2help/where2help#153]
The [LICENSE](https://github.com/where2help/where2help/commits/master/LICENSE.md) file has first been added to the repository on Nov 2, 2015. Before that, no explicit license was published but I'm assuming the whole thing was planned as an open source project from the beginning. Is that right? Do all contributors before that date agree that their code is licensed under the AGPL? Was this discussed at the hackathon maybe?

**Comment by haslinger** [comment]
Absolutely. It was always clear, that this was open source, we created (and still create it) with Vienna in mind, but also thinking about all the other cities, that could be using it.

We had an in person meeting right after the hackathon celebating our win, where everybody was attending. I brought up that we were missing a proper license file, suggested the licence and added the file afterwards. If anybody would be complaining, I could always remind them of the meeting at "Magdas Hotel".
Technically, the code was in public domain before, because it was lacking a license file. The code was published on the first day of the hackathon within two hours, so there was never code that was private or existing under a closed license.

**Comment by klappradla** [comment]
**Plus:** when we did a rewrite, we removed everything from the repo and started from scratch. So for the current version, everything was under the proper license from the first LOC on.

**Comment by groe** [comment]
Thanks for your answers! @haslinger @klappradla
