### ISSUE TITLE
wordings

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#177]
Some of the wordings need to be changed. Don´t really know how to best put this in here, so for now, there is a pdf attached. Red text should replace the original one.
[prot_wordings w2h_20160722.pdf](https://github.com/where2help/where2help/files/378352/prot_wordings.w2h_20160722.pdf)

**Comment by votexx** [comment]
Adopt the text of social sharing when participating in an event to: "Schau - ich helfe mit!"
![w2h_social sharing_20160722](https://cloud.githubusercontent.com/assets/19605344/17059838/631b06a8-5027-11e6-8841-d53c145d449b.PNG)

**Comment by haslinger** [comment]
Note to self: I'm currently at 1.2.5 (page 5), closing issue requires detailed comment here, esp. on 1.2.4, where that error is displayed one step later.

**Comment by haslinger** [comment]
* ad 1.2.3: "Frage: Lässt sich eine „Aktivierungs-Mail“ einbauen?" 

@votexx Not sure, what is meant here. It was a request by FSW, that NGOs have to be confirmed by an admin account, as far as we remember.

* ad 1.2.4: The error message, you requested now shows up after you tried to login. Clicking the activation link for a second time gives you the old message, that you already confirmed your email and you should try to login. I don't see an easy way to check for admin activation at that particular process step. (And I don't believe, that people would try to reclick there after they have been invited to login.)

Some of your change requests were not fully consistent, so I tried to make them consistent (e.g. Du / SIe, we are informal all over the app.) "Events" now all over the place instead of "Schicht", "Freiwillige/r" instead of "Helfer".

**Comment by votexx** [comment]
Hello and thx for the changes - just following up now, due to holidays and "other stuff".
- 1.2.3 - I thought it might be helpful, to send an actual "activation successfull"-mail after activation. So first NGO gets informed about "request sent" and later on about "now you can actually access the app".

I´ll try the web-interface for some minor changes (my cmd-line-skill stops at "dir C:\")

**Comment by haslinger** [comment]
Ah now I get it and implemented it. 

Note to the other developers: It was implemeted via callback in aasm which does not get called when changed via active_admin => now also implemented in callback of active admin.
Fixed via: c1a665c02
