### ISSUE TITLE
"Touch Icon" for SmartPhones

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#183]
One more point on the wish-list :-)
- Feature to create a "touch icon" on the smart-phone dashboard ([example ](http://fluidmobile.de/iphone-ipad-touch-icon-fuer-webseiten-erstellen/ )[in german]). 
- Maybe also possible for android?
- possibility to prompt users after logging in to create the shortcut (how can we controll, to only prompt once?)

**Comment by klappradla** [comment]
I don't and never have owned an Android phone, but I guess it's more a question of wether the mobile browser has this feature. If **Chrome** *(I think so, but not sure)* is the default one on Android, than it [should be available](https://developer.chrome.com/multidevice/android/installtohomescreen).

Adding the necessary meta tags and images for this makes total sense.

Prompting users after login is also quite easy. We know which device they're on and we can by storing values in session or database also only prompt them once.
What's more difficult here in my opinion: what do you show them? A whole tutorial on how to set this up? Since this involves multiple steps, including leaving the popup, how should they be able to get back to the instructions?

I think this is also a hint, that the application really lacks a **FAQ** section.

**Comment by haslinger** [comment]
Chrome is not the default browser on Android, most of the times it's just 'Web Browser'.
And either way I would be highly annoyed if a website cluttered my screen with an icon I didn't ask for. That's what bookmarks are for. And I have never seen a single website trying to create such an icon. 
Don't annoy your users, especially, if they are volunteers...

**Comment by klappradla** [comment]
It's not possible to add these icons automatically, at least not on iOS or Android @haslinger. The user's have to do it themselves - it's kind of a bookmark for these devices.

**Comment by votexx** [comment]
To sum it up: 
- feature has to be implemented for different browsers
- every browser already has a bookmark-function
- icon cannot be placed automatically (would be strange as well)
- endless prompt is annoying

I guess that one´s closed...

**Comment by groe** [comment]
I just talked to Michi H. about this and we tried to come up with a solution that does not annoy users but still encourages them to add the app to their home screen (which could result in better user retention).

How about this?

* When signing up on mobile (or maybe after the confirmation link has been clicked on a mobile device), a "how to install where2help on your home screen" howto page could be shown.
* Once the account is created (or activated) that page will never interrupt the user again.
* A link in the footer "Add where2help to your home screen" could be added that refers to the howto page as well, for future reference.
* If possible the howto page should detect the users browser and highlight the corresponding part of the howto.
* Or maybe use a script like [this one](http://cubiq.org/add-to-home-screen)?

@votexx Can we reopen this issue for discussion?

**Comment by klappradla** [comment]
@groe sounds reasonable - let's put this up for discussion

**Comment by haslinger** [comment]
The demo of the script mentioned above doesn't work on my Phone (Samsung Galaxy S4 mini, not rooted) with Chrome.

In contrast Chrome's built in "Add to Home Screen" (translated from "Zu Startbildschirm hinzufügen")  works nicely and needs no change in the application. 

I'm not sure, if users need to be coached on that or putting it the other way round: I'm not sure, if users that need to be coached to use it will get the instructions.

**Comment by klappradla** [comment]
Thanks for the additional information *"from the field"* @haslinger 😉 

All in all, it seems we a) don't really need this and b) if we would implement it in some way it would be too hard to test and maintain. So I guess we can close this one.
