### ISSUE TITLE
Mobile / on the events page: Scrolling not possible because of map

### ISSUE THREAD

**Issue by groe** [where2help/where2help#203]
When opening the detail page for an event on mobile, it's hard to scroll because instead of scrolling through the page you move the map window around. Can we move the map down a bit, below the other elements on the page?

(creating this issue in behalf of michi h. from FSW)

**Comment by klappradla** [comment]
Yes, I've seen that as well - sometimes even an issue on desktop. However
> move the map down a bit
probably won't solve it for good, we would need to shove it down to the bottom...

Maybe it can also be solved by just setting a different focus or changing the map behavior. We need to investigate on this.

**Comment by Thrillberg** [comment]
I took a look at this and thought that freezing the map at its starting zoom level might be a good approach. Is there any reason we might want to allow the user to zoom in and out on the map? Here's the fix I made: https://github.com/Thrillberg/where2help/tree/map_scrolling_on_events_page_fix_203

What do you think?

**Comment by haslinger** [comment]
Interesting idea. And better than any ideas I had up to now. What do the others think?

**Comment by klappradla** [comment]
Hey @Thrillberg thanx for your solution 👍 
We actually had it like this in the beginning (months / years ago). However, I consider zooming in and out a key feature of the map, since this is the major way to go for people to figure out **where exactly** in the context of the city a location is, to then zoom back in and get the details on how to get there.
That's also why we for now lived with the tradeoff of not having the best scrolling experience on this page.

The option I find most interesting at the moment (copied from Facebook) would be to hide and expand the map on click / tab.

**Comment by Thrillberg** [comment]
@klappradla Thanks for the additional info on this. I'd be happy to try to put together a map that can be activated by a click. You mentioned that Facebook has this feature--can you tell me how to find it? I poked around a little over there but couldn't find what exactly you were referring to.

**Comment by Thrillberg** [comment]
I've submitted a PR (https://github.com/where2help/where2help/pull/218) that toggles the ability to zoom on the map with scrolling based on whether you have clicked the map to activate it or not. It also includes a blue border when activated. I wasn't sure if we wanted to add text to indicate how to activate the map or just hope users will figure it out. Any insights?

**Comment by klappradla** [comment]
Closing this thanx to @Thrillberg 🎉
