### ISSUE TITLE
Wrong domain in mailer "from" address and canonical tags

### ISSUE THREAD

**Issue by groe** [where2help/where2help#205]
The following files contain "where2help.at" instead of "where2help.wien" at some place:

* app/mailers/admin_mailer.rb (from-address)
* app/mailers/ngo_mailer.rb (from-address)
* app/mailers/user_mailer.rb (from-address)
* public/404.html (canonical tag)
* public/422.html (canonical tag)
* public/500.html (canonical tag)

My suggestion would be to centralize the from-address setting in an initializer. And regarding the canonical tag: What's the purpose of it on an error page?

**Comment by klappradla** [comment]
Hey @groe, sorry for the late response - had some troubles with my computers 🙈 (but back on track now).

As for the `from-addresses`: since it will probably always be the same, just go ahead and delete all the explicit
```ruby
default from:
```
And just set a global default in `<environment>.rb` like:
```ruby
config.action_mailer.default_options = {
  from: 'where2help <no-reply@staging-where2help.herokuapp.com>',
  reply_to: 'where2help <where2helpinaustria@gmail.com>'
}
```
If you think an initializer is better solution - feel free to implement it like this. I would go for `config.action_mailer` since I think it's the most straight forward way.


As for the `canonical` tags, I don't know why we have them and if they're necessary on not. @waldgruber should know the details here.

**Comment by groe** [comment]
You are right, the evironment config is even more straight forward. Thanks!
