### ISSUE TITLE
Continuously search for volunteers without specific announced dates

### ISSUE THREAD

**Issue by groe** [where2help/where2help#223]
Turns out many NGOs in addition to the existing functionality would like to use W2H to search for volunteers on a regular basis, i.e. without specific announced dates.

For instance, some NGOs need volunteers that help them with transport tasks, but the actual date/time of the transport is not fixed. So volunteers would sign up for it and the NGO then contacts them to discuss when they have time etc.

There are already several events from NGOs in W2H's production instance with "fake" dates, which they apparently used to search continously, but this is of course not ideal. For the user, it means "Here's the date, oh nevermind, it's just ANY date" and for the NGO it's quite cumbersome to set up all the shifts and keep adding new ones (so they will stop doing it).

Also, in the past there was another project which helped some of the viennese NGOs find volunteers for ongoing work. So the NGOs who switched over from that project to W2H pretty much expect us to support that use case as well...

So I would propose:
* Introduce a `kind` attribute to events, which can be `"fixed_dates"` or `"ongoing"` (can be chosen in the event creation form)
* Depending on the `kind` of event, an event either has to have

  * 1+ shifts assigned (`fixed_dates`), or
  * have exactly 1 shift assigned (`ongoing`), which always starts at the current/creation date (remove the input field for that) and ends at a given future date – this is the "expiration" of the event

* Limit shift end dates to `ends_at < starts_at+1.year`
* In the events list, add tabs or [segmented control](https://developer.apple.com/ios/human-interface-guidelines/ui-controls/segmented-controls/)-like buttons to the top, to allow users to switch between fixed-dates and ongoing-work event lists (the exact wording is still WIP). The default pre-selected is fixed-dates.
* At the end of the fixed-dates list, add a hint like
  "Want to contribute on a regular basis? _» Show ongoing events_" (wording WIP...)

What are your opinions on that? Since this is one of the main pain points for NGOs right now, I'd be happy to implement this asap.

**Comment by klappradla** [comment]
Thanx for the detailed explanation @groe 👍  - I think I got the NGOs' problem and the deferred use case.

I also like your proposed solution! Sounds decent, especially how you want to tackle the events view for volunteers introducing the *segmented control* button and the *"want to contribute on a regular basis"* thing. I just realized a tiny bug on the event's list though: it shows wrong times (only the first shift) - I will file an issue and fix it myself at Ruby Habits this week (it's only a view problem, nothing more).
This said, the volunteers' event list is *"only"* an aggregator, showing events with available shifts sorted by the time of the first available one. You'll probably need to come up with something slightly different for these `ongoing` event types and eventually also reflect this on the NGOs' list views. However, that's a tiny detail and not too hard I guess.

Besides that, interesting approach with the `kind` attribute. I would have straight gone for STI on the event model. What's the reason for your approach?

**Comment by groe** [comment]
Thanks for reviewing it @klappradla!

You're right, we could use STI for it as well. The benefit of using the `kind` attribute is that if we ever need to introduce another additional field to further differentiate events (say, based on how volunteers should sign up), that's possible, while with STI we would be restricted by the "every class has only 1 superclass" inheritance restriction. Thinking about it, naming it `shifts_kind` instead of `kind` might make that more clear.

**Comment by haslinger** [comment]
I finally took the time to properly read this (shame on me). I think it's quite hard to make that use case obvious for new comers. My first reaction was - why on earth would I sign up for a non fixed task?
I was thinking of non-fixed means moving target, but it also can mean negotiable.  And to get this across could be a challenge. 
I feel ongoing or recurring here is misleading, because both can be set up with the existing feature, adding extra shifts as you go. But _negotiable_ is an absolute valid point, even the other way round: You cannot guarantee to stop by at x, you come after work, whenever the boss lets you go. 
I believe common German term for this behaviour is "Termin auf Vereinbarung".

**Comment by klappradla** [comment]
Would you then also see the state of the volunteer as something like *"Auf Abruf"* / *"In Bereitschaft"*?

Because to me from the side of volunteers, this feature in general sounds more like: put your name on a list to be contacted for a certain type of event at a fixed location.

**Comment by pferdefleisch** [comment]
I am working on some wireframes for this.

Since the NGO's contact the volunteers individually, I will not include `Anzahl benötigter Freiwilliger`.

The app can also be used (it's main point I believe) to manage who is coming to the events. This is a noop in this ongoing feature. Does it matter that the NGO's will have to manage the volunteers for themselves?

![ngo events list](https://cloud.githubusercontent.com/assets/175984/20479443/e20b3f0e-afe6-11e6-8934-b0484bd665d3.png)
![ongoing new view](https://cloud.githubusercontent.com/assets/175984/20479445/e20d416e-afe6-11e6-82dc-2eaa93e7794a.png)
![volunteer events list](https://cloud.githubusercontent.com/assets/175984/20479444/e20c5330-afe6-11e6-9204-189f32c6381d.png)
![volunteer events list ongoing](https://cloud.githubusercontent.com/assets/175984/20479446/e20d6108-afe6-11e6-9834-15886d5a4c9b.png)

**Comment by pferdefleisch** [comment]
![volunteer events list ongoing detail](https://cloud.githubusercontent.com/assets/175984/20479726/f1b0f024-afe7-11e6-9673-98963280bb65.png)

**Comment by where2help-fsw** [comment]
We think that the Number of Volunteers searched would be still important for the ngo. If you take a look at the current events - sometimes just 2 volunteers needed, sometimes the ngo is looking for 20 persons.  In the case "Dauerhafter Einsatz" the ngo has to organise the volunteers themselves but we still want to “produce” a list with names and contact Information for the ngo.
Wording: "Konkreter Einsatz" (instead of "Aktueller Einsatz") and "Dauerhafter Einsatz" for "ongoing"
Do you Need further Feedback?
Thx! :)

**Comment by klappradla** [comment]
Looks good @pferdefleisch 🚀 
Also +1 on skipping the `volunteers_needed` part - this is not really doable for these types of events and truly won't make sense here. As for the `list of names and contact information`, no worries, this will of course still be available to the NGOs @where2help-fsw: volunteers still sign up or better to say *"write their name on the list"*.

**Comment by pferdefleisch** [comment]
@where2help-fsw, @klappradla 
It sounds like you both are saying the opposite.

1. Do I need to give a field of "Anzahl benötigter Freiwilliger"?
2. If yes, should the event be hidden if it reaches the max? (no idea if this makes sense)
3. Thanks for the translations (I will need these).

**Comment by klappradla** [comment]
I don't think we're saying the opposite, *(please correct me if I'm wrong @where2help-fsw)*

> In the case "Dauerhafter Einsatz" the ngo has to organise the volunteers themselves but we still want to “produce” a list with names and contact Information for the ngo.

This to me clearly sounds like **"no volunteers_needed"** number, but still list all volunteers who participate - as it is already done for normal shifts/events.

**Comment by pferdefleisch** [comment]
I just spoke with Michael and I get it now.

The volunteers needed in this context is more of a "How many volunteers did we say we needed?" sort of thing. So I will just keep it as `volunteers_needed` but show the ones with more `volunteers_needed` than `volunteers_count` in the list and somehow (not sure how yet) make this obvious in either naming or wordy comments.

I'm still not sure whether it makes sense to create a new kind of event or create one special kind of shift.
Shifts don't make sense to me in this context so I am very likely to go with a new event type unless someone has a great argument otherwise.

**Comment by klappradla** [comment]
Well, you're right, a `shift` does not make too much sense here domain wise. However, `volunteers_needed` and `volunteers_count` are actually attributes of a `shift`, `events` just aggregate their values.

So yes, I also think introducing a new type of `event` goes into the right direction. Not sure anymore about STI though if it would mean to replicate attributes from the `shift` model for the `event` model.
