### ISSUE TITLE
Mailers should not be invoked in Model callbacks

### ISSUE THREAD

**Issue by groe** [where2help/where2help#248]
To avoid accidental sending of notification emails, we should not use model callbacks to send emails. Instead, the **controller** or the **operation** should do it.

Also, `letter_opener` might still be helpful to catch these kind of problems early.

**Comment by pferdefleisch** [comment]
This isn't going to be so fun because this is happening in `accepts_nested_attributes_for`.
I'd almost rather just leave it. The fix (without form objects) will be pretty ugly.

**Comment by pferdefleisch** [comment]
Everyone is sent a notification every time this is saved. That can't be what we want. So what I will do is add the same checkbox from ongoing events and then update everyone if the ngo wants to.

This is also probably why letter_opener was pulled out earlier. I just got attacked with tabs!

Changing the title of the issue.

**Comment by pferdefleisch** [comment]
Nevermind, adding new issue, doesn't make sense to change the name.

**Comment by pferdefleisch** [comment]
If we were to fix this problem, it would take a lot of work and @groe and I have decided that it isn't worth the effort for the perceived benefits.

But I did change the `before_update` to an `after_update` because everyone was getting an email, even if you just edited the event, didn't change anything and saved. So we got one win :)
