### ISSUE TITLE
NGOs can sign in even if they haven't confirmed their email yet

### ISSUE THREAD

**Issue by groe** [where2help/where2help#263]
For NGOs two conditions must be met to be able to log in:

1. Email confirmed
2. Admin confirmed

However, the first one doesn't seem to be checked currently?

**Comment by pferdefleisch** [comment]
The reason it is working like this is because the admin section confirms the NGO which is the same apparatus used to confirm email addresses. I don't know how to proceed here, but I will update the issue when I make a decision.

I will likely create a new `admin_confirmed_at:datetime` or `admin_confirmed:boolean` on the NGO model, but I'm not really sure yet what that will mean for the rest of the system.
This might be a pain in the butt.

**Comment by pferdefleisch** [comment]
I figured it out. No need to think about it and comment ;)
