### ISSUE TITLE
API token authentication

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#78]
We will change the way we handle token authentication for the API.
We will drop using devise token auth in favor for Rails 5's Token as described in the [API Docs](http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html).

The following endpoints will be implemented:

- [x] events, only in future, only with helpers needed, including one attribute, if current_user is assigned, including attribute of helpers needed
- [x] events, only in future, only with helpers needed, only attributes id and number of helpers needed
- [x] single event, attribute, if current_user assigned
- [x] create new user
- [x] change password
- [x] deactivate account
- [x] logout
- [x] login
- [x] password reset for email address
- [x] resend confirmation email
- [x] sign up for shift
- [x] withdraw from shift

**Comment by markusrubey** [comment]
Knowing everything is work in progress, so just from playing around a bit:

- Can't find `/api/v1/users/registrations ` but `/api/v1/registrations` works

- Would propose names like `/register` & `/unregister` or `/create` & `/delete` instead of `/registrations` & `/destroy`

- Would expect an error like "_Email normal-user@example.com is not confirmed_" for `/login`

- Follow up: Will I be able to request a new confirmation-email through the API? Or let's say a user misspelled his email on registration and therefore doesn't get the confirmation-email. Should the user be able to correct the email somehow? 

- I think I couldn't confirm my email for registration through the link in the confirmation-email

**Comment by haslinger** [comment]
* Yeah, that's inconsistent, now /users/register (note to self: I move the action from Devise to the users namespace)
* Why not, changed to /users/register & users/unregister
* I see, I will now always return 200:OK to be able to return a proper error message
* Yeah, that's missing (added task above). No correction for emails, just register with the correct email address. We could build a cleanup task to remove non confirmed emails after - say - a month.
* That's interesting, because it worked just now for me. Any errors? But I think the confirmation message is missing on the view - I will open an issue for that.

**Comment by markusrubey** [comment]
Nice, thanks! I am able to log in now.

- Nope, I don't mind `delete` as method

- I could in response to the error show something like "Check this email... for confirmation" with a button or a message saying "change your email if it's wrong". If change-button is clicked -> delete the account for the wrong email -> show empty register screen again

**Comment by haslinger** [comment]
I get the idea and you get the error message already {logged_in: false, user: "not_confirmed"} 
But you should not be able to delete an account, that's not confirmed. Because it could be created by the legitimate owner. So just create another one and don't worry about the few extra records on the database.

**Comment by markusrubey** [comment]
I see, I'll let you handle the cleanup then :-P 

Do we stick to returning the user-model for a successful login?

**Comment by haslinger** [comment]
Oops, sure, fixed.
